name: React CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        # Ensure react-router-dom is installed
        if ! npm list react-router-dom >/dev/null 2>&1; then
          npm install react-router-dom
        fi

    - name: Verify React Router installation
      run: |
        if ! npm list react-router-dom >/dev/null 2>&1; then
          echo "react-router-dom is not installed!"
          exit 1
        fi
        echo "react-router-dom is properly installed"

    - name: Create Router config for GitHub Pages
      run: |
        echo "Creating public/404.html for client-side routing"
        cat > public/404.html << 'EOL'
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="utf-8">
            <title>Redirecting...</title>
            <script>
              sessionStorage.redirect = location.href;
            </script>
            <meta http-equiv="refresh" content="0;URL='/'">
          </head>
          <body>
            Redirecting...
          </body>
        </html>
        EOL

    - name: Run tests
      run: npm test
      env:
        CI: true

    - name: Build
      run: npm run build
      env:
        CI: true
        PUBLIC_URL: "/${{ github.event.repository.name }}"

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './build'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
